config/routes.rb
Rails.application.routes.draw do
  resources :articles do
  collection do
    get 'delete_all'
  end
end
resources :users, only: [:create, :index] do
    collection do
      post 'confirm'
      post 'login'
    end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  namespace :api do 
    namespace :v1 do 
     resources :articles, only: [:index, :create, :destroy, :update, :show]
    end 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	# for handling the upload we need to mount the uploader for image field
# :image (our field in the table for storing the image data)
# ArticleUploader (we have created it above)
mount_uploader :image, ArticleUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates_presence_of :email
	validates_uniqueness_of :email, case_sensitive: false
	validates_format_of :email, with: /@/

	before_save :downcase_email
	before_create :generate_confirmation_instructions

	def downcase_email
  		self.email = self.email.delete(' ').downcase
	end

	def generate_confirmation_instructions
  		self.confirmation_token = SecureRandom.hex(10)
  		self.confirmation_sent_at = Time.now.utc
	end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
   before_action :authenticate_request! 
  def index
    render json: Article.all
  end

  def create
    article = Article.new(article_params)
    article.remote_image_url = params[:image]
    article.save
    render json: {title: "success"}
  end

  def destroy
    Article.destroy(params[:id])
  end

  def show
    article = Article.find(params[:id])
    render json: article
  end


 

  def update
    article = Article.find(params[:id])
    article.update_attributes(article_params)
    render json: article
  end

  private
     def article_params
      params.require(:article).permit(:title, :content, :image)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
require 'json_web_token'
	# protect_from_forgery with: :null_session
    protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  # require 'json_web_token'

  protected
  # Validates the token and user and sets the @current_user scope
  def authenticate_request!
    if !payload || !JsonWebToken.valid_payload(payload.first)
      return invalid_authentication
    end

    load_current_user!
    invalid_authentication unless @current_user
  end

  # Returns 401 response. To handle malformed / invalid requests.
  def invalid_authentication
    render json: {error: 'Invalid Request'}, status: :unauthorized
  end

  private
  # Deconstructs the Authorization header and decodes the JWT token.
  def payload
    auth_header = request.headers['Authorization']
    token = auth_header.split(' ').last
    JsonWebToken.decode(token)
  rescue
    nil
  end

  # Sets the @current_user with the user_id from payload
  def load_current_user!
    @current_user = User.find_by(id: payload[0]['user_id'])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  def delete_all
    Article.delete_all
    redirect_to root_path
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
		render json:  {user: @users}
	end

	def create
 		user = User.new(user_params)
 		user.password = params[:password]
  		if user.save
    		render json: {status: 'User created successfully'}, status: :created
  		else
    		render json: { errors: user.errors.full_messages }, status: :bad_request
  		end
	end


	def login
	  user = User.find_by(email: params[:email].to_s.downcase)

	  if user && user.authenticate(params[:password])
	      auth_token = JsonWebToken.encode({user_id: user.id})
	      render json: {auth_token: auth_token}, status: :ok
	  else
	    render json: {error: 'Invalid username / password'}, status: :unauthorized
	  end
	end

private

def user_params
  params.require(:user).permit(:email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>
<h2><%= link_to 'Delete all', delete_all_articles_path %></h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.image %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @article.image %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<h2><%= @article.title %></h2>
<p><%= @article.content %></p>
<!-- Show the image here -->
<%= cl_image_tag @article.image.url width: '200px', height: '200px' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloudinary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>